(() => {
  const URL=window.PANEL_SUPABASE_CONFIG.url;
  const KEY=window.PANEL_SUPABASE_CONFIG.publishableKey;
  const db=window.createPanelSupabaseClient(), user=getUser(), level=getRole();
  let posts=[], filter='all', editing=null, draft=null;
  const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const invoke=async(body)=>{const token=localStorage.getItem('discord_access_token');if(!token){requestFreshLogin();throw new Error('Sesiunea Discord lipsește. Se redeschide autentificarea.')}const res=await fetch(`${URL}/functions/v1/manage-community-posts`,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY,Authorization:`Bearer ${KEY}`},body:JSON.stringify({...body,access_token:token})});let json={};try{json=await res.json()}catch{json={}}if(res.status===401){requestFreshLogin();throw new Error('Sesiunea Discord a expirat. Se redeschide autentificarea.')}if(!res.ok)throw new Error(json.error||json.message||`Operația a eșuat. Cod HTTP: ${res.status}`);return json};
  function requestFreshLogin(){sessionStorage.setItem('panel_return_after_login',location.href);setTimeout(()=>{location.href='login.html'},700)}

  async function load(){const [postResult,optionResult,reactionResult,voteResult,userResult]=await Promise.all([db.from('community_posts').select('*').order('created_at',{ascending:false}),db.from('community_poll_options').select('*'),db.from('community_reactions').select('*'),db.from('community_poll_votes').select('*'),db.from('users').select('discord_id,display_name,username')]);const error=postResult.error||optionResult.error||reactionResult.error||voteResult.error;if(error){console.error('Eroare încărcare anunțuri:',error);$('#feed').innerHTML=`<div class="empty">Nu pot citi datele din Supabase: ${esc(error.message||error.code||'eroare necunoscută')}</div>`;return}const voters=userResult.data||[];posts=(postResult.data||[]).map(post=>({...post,community_poll_options:(optionResult.data||[]).filter(x=>x.post_id===post.id),community_reactions:(reactionResult.data||[]).filter(x=>x.post_id===post.id),community_poll_votes:(voteResult.data||[]).filter(x=>x.post_id===post.id),community_voters:voters}));render();const wanted=new URLSearchParams(location.search).get('post');if(wanted)setTimeout(()=>{const element=document.getElementById(`post-${wanted}`);if(element){element.classList.add('highlight');element.scrollIntoView({behavior:'smooth',block:'center'})}},100)}
  function render(){const visible=posts.filter(p=>filter==='all'||p.audience===filter||(filter==='poll'&&p.post_type==='poll'));$('#feed').innerHTML=visible.length?visible.map(card).join(''):'<div class="empty">Nu există postări în această categorie.</div>';bindCards()}
  function card(p){const own=String(p.author_discord_id)===String(user.discord_id||user.id),manage=own||level===7,reactions=['👍','❤️','✅','🤔'];const totals=Object.fromEntries(reactions.map(r=>[r,p.community_reactions.filter(x=>x.reaction===r).length]));const mine=new Set(p.community_reactions.filter(x=>String(x.user_discord_id)===String(user.discord_id||user.id)).map(x=>x.reaction));const votes=p.community_poll_votes||[],myVote=votes.find(v=>String(v.user_discord_id)===String(user.discord_id||user.id)),people=p.community_voters||[];const poll=p.post_type==='poll'?`<div class="poll">${(p.community_poll_options||[]).sort((a,b)=>a.position-b.position).map(o=>{const optionVotes=votes.filter(v=>v.option_id===o.id),pc=votes.length?Math.round(optionVotes.length*100/votes.length):0,names=optionVotes.map(v=>{const person=people.find(x=>String(x.discord_id)===String(v.user_discord_id));return esc(person?.display_name||person?.username||v.user_discord_id)});return `<div class="poll-choice"><button class="poll-option" data-vote="${o.id}"><span class="poll-bar" style="width:${pc}%"></span><span class="poll-content"><span>${esc(o.option_text)}${myVote?.option_id===o.id?' ✓':''}</span><b>${pc}% · ${optionVotes.length}</b></span></button><details class="poll-voters"><summary>👥 Vezi cine a votat (${optionVotes.length})</summary><div>${names.length?names.map(n=>`<span>${n}</span>`).join(''):'<em>Nu a votat nimeni.</em>'}</div></details></div>`}).join('')}</div>`:'';return `<article id="post-${p.id}" class="post"><div class="community-head"><div class="badges"><span class="badge ${p.audience}">${p.audience==='family'?'Familie':'Mecanici'}</span><span class="badge">${p.post_type==='poll'?'Sondaj':p.post_type==='question'?'Întrebare':'Anunț'}</span></div></div><h3>${esc(p.title)}</h3><div class="post-body">${esc(p.content)}</div>${poll}<div class="meta">${esc(p.author_name)} · ${new Date(p.created_at).toLocaleString('ro-RO')}</div><div class="community-actions"><div class="reactions">${reactions.map(r=>`<button class="reaction ${mine.has(r)?'selected':''}" data-react="${r}">${r} ${totals[r]}</button>`).join('')}</div>${manage?`<div class="owner-actions"><button class="text-action" data-edit="${p.id}">Editează</button><button class="text-action danger" data-delete="${p.id}">Șterge</button></div>`:''}</div></article>`}
  function bindCards(){$$('[data-react]').forEach(b=>b.onclick=()=>withFeedback(b,act('react',{post_id:b.closest('.post').id.slice(5),reaction:b.dataset.react})));$$('[data-vote]').forEach(b=>b.onclick=()=>withFeedback(b,act('vote',{post_id:b.closest('.post').id.slice(5),option_id:b.dataset.vote})));$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Ștergi definitiv această postare?'))await act('delete',{post_id:b.dataset.delete})});$$('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit))}
  async function withFeedback(button,promise){button.style.opacity='.55';button.style.pointerEvents='none';button.disabled=true;try{await promise}finally{button.style.opacity='';button.style.pointerEvents='';button.disabled=false}}
  const $$=s=>[...document.querySelectorAll(s)];async function act(action,payload){try{await invoke({action,...payload});await load()}catch(e){alert(e.message)}}
  function option(value=''){const row=document.createElement('div');row.className='poll-option-row';row.innerHTML=`<input class="poll-input" maxlength="120" value="${esc(value)}" placeholder="Opțiune"><button type="button" class="text-action danger">×</button>`;row.querySelector('button').onclick=()=>row.remove();$('#poll-options').appendChild(row)}
  function openEdit(id){const p=posts.find(x=>String(x.id)===String(id));editing=p.id;$('#form-heading').textContent='Editează postarea';$('#post-type').value=p.post_type;$('#post-type').disabled=true;$('#post-title').value=p.title;$('#post-content').value=p.content;$('#poll-wrap').hidden=p.post_type!=='poll';$('#poll-options').innerHTML='';(p.community_poll_options||[]).sort((a,b)=>a.position-b.position).forEach(o=>option(o.option_text));$('#post-modal').hidden=false}
  document.addEventListener('DOMContentLoaded',()=>{$('#user-display-name').textContent=user.display_name||user.username||'Utilizator';$('#user-role').textContent=user.role||user.default_role||'Rol';$('#user-avatar').src=user.avatar||user.avatar_url||'';$('#create-button').hidden=level<4;$('#create-button').onclick=()=>{editing=null;$('#post-form').reset();$('#post-type').disabled=false;$('#poll-options').innerHTML='';$('#poll-wrap').hidden=true;$('#post-modal').hidden=false};$('#post-type').onchange=e=>{$('#poll-wrap').hidden=e.target.value!=='poll';if(e.target.value==='poll'&&!$('#poll-options').children.length){option();option()}};$('#add-option').onclick=()=>option();$('[data-close]').onclick=()=>$('#post-modal').hidden=true;$('[data-back]').onclick=()=>{$('#audience-modal').hidden=true;$('#post-modal').hidden=false};$('#post-form').onsubmit=e=>{e.preventDefault();const options=$$('.poll-input').map(x=>x.value.trim()).filter(Boolean);if($('#post-type').value==='poll'&&options.length<2)return alert('Adaugă minimum două opțiuni.');draft={post_type:$('#post-type').value,title:$('#post-title').value.trim(),content:$('#post-content').value.trim(),options};if(editing)return act('update',{post_id:editing,...draft}).then(()=>$('#post-modal').hidden=true);$('#post-modal').hidden=true;$('#audience-modal').hidden=false};$$('[data-audience]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await act('create',{...draft,audience:b.dataset.audience});$('#audience-modal').hidden=true}catch(e){alert(e.message)}finally{b.disabled=false}});$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});load();db.channel('community-live').on('postgres_changes',{event:'*',schema:'public',table:'community_posts'},load).subscribe()});
  document.head.insertAdjacentHTML('beforeend','<style>.poll-choice{display:grid;gap:6px}.poll-option{width:100%}.poll-voters{margin:0 4px 6px;color:#94a3b8;font-size:12px}.poll-voters summary{cursor:pointer;user-select:none}.poll-voters>div{display:flex;gap:6px;flex-wrap:wrap;padding:9px 0}.poll-voters span{padding:4px 8px;border:1px solid #334155;border-radius:999px;background:#0b1220;color:#cbd5e1}</style>');
  document.addEventListener('DOMContentLoaded',()=>{db.channel('community-interactions-live').on('postgres_changes',{event:'*',schema:'public',table:'community_poll_votes'},load).on('postgres_changes',{event:'*',schema:'public',table:'community_reactions'},load).on('postgres_changes',{event:'*',schema:'public',table:'community_poll_options'},load).subscribe()});
  document.addEventListener('DOMContentLoaded',()=>{const content=$('#post-content');content.required=false;content.placeholder='Conținut opțional'});
})();
