import {createClient} from 'jsr:@supabase/supabase-js@2';
import {requirePanelSession} from '../_shared/panel-session.ts';
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-panel-session','Content-Type':'application/json'};
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
const safeFetch=async(url:string,init:RequestInit={},timeout=8000)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{...init,signal:controller.signal})}finally{clearTimeout(timer)}};

Deno.serve(async request=>{
 if(request.method==='OPTIONS')return new Response('ok',{headers});if(request.method!=='POST')return reply({error:'Metodă invalidă.'},405);
 try{
  const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')??'{}').default;if(!key)throw new Error('Cheia secretă Supabase lipsește.');
  const db=createClient(Deno.env.get('SUPABASE_URL')!,key),session=await requirePanelSession(db,request,7),body=await request.json(),organizationId=session.organization_id;const platformOwners=String(Deno.env.get('PLATFORM_OWNER_DISCORD_IDS')||'').split(',').map(value=>value.trim()).filter(Boolean);if(!platformOwners.includes(String(session.discord_id)))return reply({error:'Această funcție este rezervată administratorului platformei.'},403);
  const load=async()=>{const [{data:organization},{data:settings},{data:guilds},{data:roles},{data:platformSettings}]=await Promise.all([
   db.from('organizations').select('*').eq('id',organizationId).single(),db.from('organization_settings').select('*').eq('organization_id',organizationId).maybeSingle(),
   db.from('organization_guilds').select('*').eq('organization_id',organizationId).order('kind'),db.from('organization_role_mappings').select('*').eq('organization_id',organizationId).eq('enabled',true).order('permission_level'),db.from('app_settings').select('key,value').eq('organization_id',organizationId).in('key',['organization_access','contract_template'])]);
   return{organization,settings,guilds:guilds||[],roles:roles||[],platformSettings:Object.fromEntries((platformSettings||[]).map((item:any)=>[item.key,item.value]))};};
  if(body.action==='get'){
   const state=await load(),primary=state.guilds.find((g:any)=>g.kind==='primary'),secondary=state.guilds.find((g:any)=>g.kind==='secondary');
   const mappings=[1,2,3,4,5,6,7].map(level=>{const p=state.roles.find((r:any)=>r.guild_id===primary?.guild_id&&Number(r.permission_level)===level),s=state.roles.find((r:any)=>r.guild_id===secondary?.guild_id&&Number(r.permission_level)===level);return{permission_level:level,discord_role_id:p?.discord_role_id||'',discord_role_name:p?.discord_role_name||'',discord_role_id_secondary:s?.discord_role_id||'',discord_role_name_secondary:s?.discord_role_name||'',panel_role:p?.panel_role||s?.panel_role||'',enabled:true};});
   return reply({config:{...(state.settings||{}),organization_name:state.organization.name,organization_code:state.organization.code,organization_description:state.organization.description,organization_logo:state.organization.logo_url,organization_banner:state.organization.banner_url,guild_id:primary?.guild_id||'',guild_id_secondary:secondary?.guild_id||''},mappings});
  }
  if(body.action==='discover_discord_roles'){
   const guildId=String(body.guild_id||'').trim(),bot=String(Deno.env.get('DISCORD_BOT_TOKEN')||'').trim();if(!/^\d{15,22}$/.test(guildId))return reply({error:'Guild ID invalid.'},400);if(!bot)throw new Error('DISCORD_BOT_TOKEN lipsește.');
   const [gr,rr]=await Promise.all([fetch(`https://discord.com/api/v10/guilds/${guildId}`,{headers:{Authorization:`Bot ${bot}`}}),fetch(`https://discord.com/api/v10/guilds/${guildId}/roles`,{headers:{Authorization:`Bot ${bot}`}})]);if(!gr.ok||!rr.ok)return reply({error:`Botul nu poate accesa serverul (HTTP ${!gr.ok?gr.status:rr.status}).`},400);const guild=await gr.json(),roles=await rr.json();return reply({guild:{id:guild.id,name:guild.name},roles:(roles||[]).filter((r:any)=>!r.managed&&String(r.id)!==guildId).map((r:any)=>({id:String(r.id),name:String(r.name),position:Number(r.position)})).sort((a:any,b:any)=>b.position-a.position)});
  }
  if(body.action==='save'){
   const config=body.config||{},mappings=Array.isArray(body.mappings)?body.mappings:[];if(mappings.length!==7)throw new Error('Trebuie exact șapte niveluri.');
   const primaryId=String(config.guild_id||'').trim(),secondaryId=String(config.guild_id_secondary||'').trim();if(!/^\d{15,22}$/.test(primaryId))throw new Error('Guild ID principal invalid.');if(secondaryId&&!/^\d{15,22}$/.test(secondaryId))throw new Error('Guild ID secundar invalid.');
   await db.from('organizations').update({name:String(config.organization_name||'').trim(),code:config.organization_code||null,description:config.organization_description||null,logo_url:config.organization_logo||null,banner_url:config.organization_banner||null,updated_at:new Date().toISOString()}).eq('id',organizationId);
   const guildRows=[{organization_id:organizationId,guild_id:primaryId,kind:'primary',enabled:true},...(secondaryId?[{organization_id:organizationId,guild_id:secondaryId,kind:'secondary',enabled:true}]:[])];
   for(const row of guildRows){const {error}=await db.from('organization_guilds').upsert(row,{onConflict:'guild_id'});if(error)throw error;}
   const {error:settingsError}=await db.from('organization_settings').upsert({organization_id:organizationId,discord_client_id:String(config.discord_client_id||'').trim(),panel_public_url:String(config.panel_public_url||'').replace(/\/$/,''),family_webhook_url:config.family_webhook_url||null,mechanics_webhook_url:config.mechanics_webhook_url||null,pontaj_webhook_url:config.pontaj_webhook_url||null,requests_webhook_url:config.requests_webhook_url||null,contracts_webhook_url:config.contracts_webhook_url||null,marketplace_webhook_url:config.marketplace_webhook_url||null,illegal_marketplace_webhook_url:config.illegal_marketplace_webhook_url||null,updated_by_discord_id:session.discord_id,updated_at:new Date().toISOString()},{onConflict:'organization_id'});if(settingsError)throw settingsError;
   await db.from('organization_role_mappings').delete().eq('organization_id',organizationId);
   const rows:any[]=[];for(const m of mappings){rows.push({organization_id:organizationId,guild_id:primaryId,discord_role_id:String(m.discord_role_id||''),discord_role_name:String(m.discord_role_name||''),panel_role:String(m.panel_role||''),permission_level:Number(m.permission_level),priority:Number(m.permission_level)*10,enabled:true});if(secondaryId&&m.discord_role_id_secondary)rows.push({organization_id:organizationId,guild_id:secondaryId,discord_role_id:String(m.discord_role_id_secondary),discord_role_name:String(m.discord_role_name_secondary||m.discord_role_name),panel_role:String(m.panel_role||''),permission_level:Number(m.permission_level),priority:Number(m.permission_level)*10,enabled:true});}
   if(rows.some(r=>!/^\d{15,22}$/.test(r.discord_role_id)||!r.discord_role_name||!r.panel_role||r.permission_level<1||r.permission_level>7))throw new Error('Una dintre mapările rolurilor este invalidă.');const {error:rolesError}=await db.from('organization_role_mappings').insert(rows);if(rolesError)throw rolesError;return reply({ok:true});
  }
  if(body.action==='diagnose'){
   const state=await load(),results:any[]=[],add=(id:string,category:string,label:string,status:string,message:string,started=Date.now())=>results.push({id,category,label,status,message,duration_ms:Date.now()-started});
   add('organization','Organizație','Numele organizației',state.organization?.name?.trim()?'ok':'error',state.organization?.name?.trim()?`„${state.organization.name}” este numele afișat membrilor autentificați.`:'Completează numele organizației.');
   add('organization-active','Organizație','Organizație activă',state.organization?.active?'ok':'error',state.organization?.active?'Organizația permite autentificarea membrilor.':'Organizația este dezactivată.');
   const accessExpiry=String(state.platformSettings?.organization_access?.expires_at||''),remaining=accessExpiry?Date.parse(accessExpiry)-Date.now():null;add('organization-expiry','Organizație','Termenul de activare',remaining===null?'warning':remaining>0?'ok':'error',remaining===null?'Nu este configurat un termen de expirare.':remaining>0?`Activă până la ${new Date(accessExpiry).toLocaleString('ro-RO')}.`:`Organizația a expirat la ${new Date(accessExpiry).toLocaleString('ro-RO')}.`);const contract=state.platformSettings?.contract_template;add('contract-template','Contracte','Șablonul organizației',contract?.title&&contract?.template?'ok':'warning',contract?.title&&contract?.template?`Șablon activ: ${contract.title}.`:'Nu este configurat un contract propriu; se folosește șablonul standard.');
   const clientId=String(state.settings?.discord_client_id||''),panelUrl=String(state.settings?.panel_public_url||'');
   add('client-id','Configurare','Discord Client ID',/^\d{15,22}$/.test(clientId)?'ok':'error',/^\d{15,22}$/.test(clientId)?`Client ID configurat: ${clientId}.`:'Discord Client ID lipsește sau este invalid.');
   let validPanelUrl=false;try{const parsed=new URL(panelUrl);validPanelUrl=['http:','https:'].includes(parsed.protocol)}catch{}add('panel-url','Configurare','Adresa publică a panelului',validPanelUrl?'ok':'error',validPanelUrl?panelUrl:'URL-ul public al panelului lipsește sau este invalid.');
   const primary=state.guilds.find((g:any)=>g.kind==='primary'&&g.enabled!==false);add('guild','Discord','Serverul principal',primary?'ok':'error',primary?`Guild configurat: ${primary.guild_name||primary.guild_id}.`:'Serverul principal lipsește sau este dezactivat.');
   const bot=String(Deno.env.get('DISCORD_BOT_TOKEN')||''),owners=String(Deno.env.get('PLATFORM_OWNER_DISCORD_IDS')||''),cron=String(Deno.env.get('CRON_SECRET')||'');
   add('bot-secret','Secrete','Token bot Discord',bot?'ok':'error',bot?'DISCORD_BOT_TOKEN este prezent.':'DISCORD_BOT_TOKEN lipsește.');add('owner-secret','Secrete','Proprietarul platformei',owners?'ok':'error',owners?'PLATFORM_OWNER_DISCORD_IDS este configurat.':'PLATFORM_OWNER_DISCORD_IDS lipsește.');add('cron-secret','Secrete','Protecția automatizării',cron?'ok':'error',cron?'CRON_SECRET este prezent.':'CRON_SECRET lipsește.');
   if(primary&&bot){const started=Date.now();try{const [guildResponse,rolesResponse]=await Promise.all([safeFetch(`https://discord.com/api/v10/guilds/${primary.guild_id}`,{headers:{Authorization:`Bot ${bot}`}}),safeFetch(`https://discord.com/api/v10/guilds/${primary.guild_id}/roles`,{headers:{Authorization:`Bot ${bot}`}})]);add('bot-guild-access','Discord','Accesul botului la server',guildResponse.ok&&rolesResponse.ok?'ok':'error',guildResponse.ok&&rolesResponse.ok?'Botul vede serverul și lista de roluri.':`Discord a răspuns cu HTTP ${!guildResponse.ok?guildResponse.status:rolesResponse.status}.`,started)}catch{add('bot-guild-access','Discord','Accesul botului la server','error','Botul nu poate contacta serverul Discord sau cererea a expirat.',started)}}
   const primaryRoles=state.roles.filter((r:any)=>r.guild_id===primary?.guild_id),levels=new Set(primaryRoles.map((r:any)=>Number(r.permission_level)));
   add('roles-count','Roluri Discord','Rolurile configurate',primaryRoles.length?'ok':'error',primaryRoles.length?`${primaryRoles.length} roluri Discord configurate pe ${levels.size} niveluri de acces.`:'Nu este configurat niciun rol Discord.');
   for(const [index,role] of primaryRoles.entries()){const valid=/^\d{15,22}$/.test(String(role.discord_role_id))&&String(role.panel_role||'').trim()&&Number(role.permission_level)>=1&&Number(role.permission_level)<=7;add(`role-${index+1}`,'Roluri Discord',role.discord_role_name||`Rolul ${index+1}`,valid?'ok':'error',valid?`Nivel ${role.permission_level} → ${role.panel_role}.`:'ID, nivel de acces sau nume în panel invalid.')}
   const webhooks=[['family_webhook_url','Anunțuri familie'],['mechanics_webhook_url','Anunțuri mecanici'],['pontaj_webhook_url','Pontaj și ture'],['requests_webhook_url','Cereri și învoiri'],['contracts_webhook_url','Contracte'],['marketplace_webhook_url','Marketplace legal'],['illegal_marketplace_webhook_url','Marketplace ilegal']];
   for(const [field,label] of webhooks){const url=String(state.settings?.[field]||''),started=Date.now();if(!url){add(`webhook-${field}`,'Webhook-uri',label,'warning','Webhook necompletat; notificările acestei secțiuni nu vor ajunge pe Discord.',started);continue;}if(!/^https:\/\/(?:canary\.|ptb\.)?discord(?:app)?\.com\/api\/webhooks\/\d+\/[\w.-]+/i.test(url)){add(`webhook-${field}`,'Webhook-uri',label,'error','Adresa nu are formatul unui webhook Discord.',started);continue;}try{const response=await safeFetch(url);add(`webhook-${field}`,'Webhook-uri',label,response.ok?'ok':'error',response.ok?'Webhook Discord valid și accesibil.':`Discord a răspuns cu HTTP ${response.status}.`,started)}catch{add(`webhook-${field}`,'Webhook-uri',label,'error','Timeout sau eroare de rețea.',started)}}
   const tables=['organizations','organization_settings','organization_guilds','organization_role_mappings','organization_members','panel_sessions','shifts','absences','app_settings','marketplace','marketplace_ilegal','profiles','illegal_locations','community_posts','admin_audit_log','panel_notifications'];
   for(const table of tables){const started=Date.now(),{error}=await db.from(table).select('*',{head:true,count:'exact'}).eq(table==='organizations'?'id':'organization_id',organizationId);add(`table-${table}`,'Baza de date',table,error?'error':'ok',error?error.message:'Tabel accesibil și izolat pe organizația activă.',started)}
   const functions=['sync-discord-role','manage-discord-config','manage-community-posts','send-discord-notification','close-expired-shifts','manage-admin-center','manage-organizations'];
   const baseUrl=String(Deno.env.get('SUPABASE_URL')||'');for(const name of functions){const started=Date.now();try{const response=await safeFetch(`${baseUrl}/functions/v1/${name}`,{method:'OPTIONS'});add(`function-${name}`,'Funcții server',name,response.ok?'ok':'error',response.ok?'Funcția este publicată și răspunde.':`HTTP ${response.status}.`,started)}catch{add(`function-${name}`,'Funcții server',name,'error','Funcția nu răspunde sau cererea a expirat.',started)}}
   if(validPanelUrl){for(const file of ['index.html','login.html','organizatii.html','diagnostic.html','js/supabase-config.js','js/panel-layout.js']){const started=Date.now();try{const response=await safeFetch(`${panelUrl.replace(/\/$/,'')}/${file}`);add(`file-${file}`,'Fișiere publice',file,response.ok?'ok':'error',response.ok?'Fișier publicat și accesibil.':`HTTP ${response.status}.`,started)}catch{add(`file-${file}`,'Fișiere publice',file,'error','Fișierul nu poate fi accesat.',started)}}}
   const summary=results.reduce((a:any,r:any)=>(a[r.status]++,a),{ok:0,warning:0,error:0});return reply({checked_at:new Date().toISOString(),results,summary});
  }
  return reply({error:'Acțiune necunoscută.'},400);
 }catch(error){console.error(error);return reply({error:error instanceof Error?error.message:'Eroare internă.'},400)}
});
