-- Jurnal administrativ și centru de notificări.
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_discord_id text not null,
  actor_name text,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.panel_notifications (
  id bigint generated by default as identity primary key,
  recipient_discord_id text,
  title text not null check (length(title) between 1 and 120),
  message text not null check (length(message) between 1 and 1000),
  level text not null default 'info' check (level in ('info','success','warning','error')),
  link text,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.panel_notification_reads (
  notification_id bigint references public.panel_notifications(id) on delete cascade,
  discord_id text not null,
  read_at timestamptz not null default now(),
  primary key (notification_id, discord_id)
);

create index if not exists audit_created_at_idx on public.admin_audit_log(created_at desc);
create index if not exists notifications_recipient_idx on public.panel_notifications(recipient_discord_id, created_at desc);

alter table public.admin_audit_log enable row level security;
alter table public.panel_notifications enable row level security;
alter table public.panel_notification_reads enable row level security;

revoke all on public.admin_audit_log, public.panel_notifications, public.panel_notification_reads from anon, authenticated;
grant select on public.admin_audit_log to anon;
drop policy if exists anon_audit_read on public.admin_audit_log;
create policy anon_audit_read on public.admin_audit_log for select to anon using (true);
